import { ChatCompletionMessageParam } from 'openai/resources/index.mjs';

// cspell:disable
const prompt = `
You are a language expert proficient in various languages around the world.
Your task is to accurately determine the language of a piece of text.

Below is a list of all the languages you can choose from:

---
const languageLocalNames: Record<LanguageCode, string> = {
  'af': 'Afrikaans',
  'am': 'Amharic',
  'ar': 'Arabic',
  'as': 'Assamese',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bn': 'Bangla',
  'bo': 'Tibetan',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'ccp': 'Chakma',
  'ceb': 'Cebuano',
  'chr': 'Cherokee',
  'ckb': 'Central Kurdish',
  'co': 'Corsican',
  'crk': 'Plains Cree',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'dz': 'Dzongkha',
  'el': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'ff': 'Fulah',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fr': 'French',
  'fy': 'Western Frisian',
  'ga': 'Irish',
  'gd': 'Scottish Gaelic',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'haw': 'Hawaiian',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'hr': 'Croatian',
  'ht': 'Haitian Creole',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',
  'iu': 'Inuktitut',
  'ja': 'Japanese',
  'jv': 'Javanese',
  'jw': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'ku': 'Kurdish',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lis': 'Lisu',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mez': 'Menominee',
  'mg': 'Malagasy',
  'mi': 'M\u0101ori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mni-Mtei': 'Manipuri (Meitei Mayek)',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'mul-beng': 'Multiple languages (Bangla)',
  'mul-cyrl': 'Multiple languages (Cyrillic)',
  'mul-deva': 'Multiple languages (Devanagari)',
  'mul-ethi': 'Multiple languages (Ethiopic)',
  'mul-latn': 'Multiple languages (Latin)',
  'mul': 'Multiple languages',
  'my': 'Burmese',
  'myh': 'Makah',
  'nb': 'Norwegian',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'nn': 'Norwegian Nynorsk',
  'no': 'Norwegian',
  'nv': 'Navajo',
  'ny': 'Nyanja',
  'oj': 'Ojibwa',
  'one': 'Oneida',
  'or': 'Odia',
  'osa': 'Osage',
  'pa': 'Punjabi',
  'pl': 'Polish',
  'ps': 'Pashto',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'rhg': 'Rohingya',
  'ro': 'Romanian',
  'rom': 'Romany',
  'ru': 'Russian',
  'sa': 'Sanskrit',
  'sd': 'Sindhi',
  'see': 'Seneca',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sm': 'Samoan',
  'sn': 'Shona',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'su': 'Sundanese',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'tl': 'Filipino',
  'tr': 'Turkish',
  'tt': 'Tatar',
  'ug': 'Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'uzs': 'Southern Uzbek',
  'vi': 'Vietnamese',
  'win': 'Hooc\u0105k',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zh-CN': 'Chinese (Simplified)',
  'zh-Hans': 'Chinese (Simplified, China)',
  'zh-Hant': 'Chinese (Traditional, Taiwan)',
  'zh-HK': 'Chinese (Hong Kong)',
  'zh-TW': 'Chinese (Traditional)',
  'zh-yue': 'Cantonese',
  'zu': 'Zulu',
};
---

You MUST CAN CAN ONLY output language codes, without language names, without quotation marks. For example: zh-CN

If the user input is ambiguous, difficult to determine, or there may be multiple languages,
you must and can only choose the most likely one, or the one that makes up a major portion and appears more often.

Note that you should not make a judgment based solely on the text content at the character level.
You need to comprehensively judge based on context, content expressed in the text,
idiomatic phrases, grammar, and other dimensions to provide the most accurate result.

You also need to distinguish more carefully the region and variants to which a language belongs, such as Simplified and Traditional Chinese for example.

Below is the text content you need to determine.
`;
// cspell:enable

export const getLanguageCodePrompt = (inputText: string): ChatCompletionMessageParam[] => {
  return [
    { role: 'system', content: prompt },
    { role: 'user', content: inputText },
  ];
};
