// cspell:disable

import { LanguageCode } from './language-code.ts';

export const languageLocalNames: Record<LanguageCode, string> = {
  'af': 'Afrikaans',
  'am': 'Amharic',
  'ar': 'Arabic',
  'as': 'Assamese',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bn': 'Bangla',
  'bo': 'Tibetan',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'ccp': 'Chakma',
  'ceb': 'Cebuano',
  'chr': 'Cherokee',
  'ckb': 'Central Kurdish',
  'co': 'Corsican',
  'crk': 'Plains Cree',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'dz': 'Dzongkha',
  'el': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'ff': 'Fulah',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fr': 'French',
  'fy': 'Western Frisian',
  'ga': 'Irish',
  'gd': 'Scottish Gaelic',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'haw': 'Hawaiian',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'hr': 'Croatian',
  'ht': 'Haitian Creole',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',
  'iu': 'Inuktitut',
  'ja': 'Japanese',
  'jv': 'Javanese',
  'jw': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'ku': 'Kurdish',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lis': 'Lisu',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mez': 'Menominee',
  'mg': 'Malagasy',
  'mi': 'M\u0101ori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mni-Mtei': 'Manipuri (Meitei Mayek)',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'mul-beng': 'Multiple languages (Bangla)',
  'mul-cyrl': 'Multiple languages (Cyrillic)',
  'mul-deva': 'Multiple languages (Devanagari)',
  'mul-ethi': 'Multiple languages (Ethiopic)',
  'mul-latn': 'Multiple languages (Latin)',
  'mul': 'Multiple languages',
  'my': 'Burmese',
  'myh': 'Makah',
  'nb': 'Norwegian',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'nn': 'Norwegian Nynorsk',
  'no': 'Norwegian',
  'nv': 'Navajo',
  'ny': 'Nyanja',
  'oj': 'Ojibwa',
  'one': 'Oneida',
  'or': 'Odia',
  'osa': 'Osage',
  'pa': 'Punjabi',
  'pl': 'Polish',
  'ps': 'Pashto',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'rhg': 'Rohingya',
  'ro': 'Romanian',
  'rom': 'Romany',
  'ru': 'Russian',
  'sa': 'Sanskrit',
  'sd': 'Sindhi',
  'see': 'Seneca',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sm': 'Samoan',
  'sn': 'Shona',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'su': 'Sundanese',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'tl': 'Filipino',
  'tr': 'Turkish',
  'tt': 'Tatar',
  'ug': 'Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'uzs': 'Southern Uzbek',
  'vi': 'Vietnamese',
  'win': 'Hooc\u0105k',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zh-CN': 'Chinese (Simplified)',
  'zh-Hans': 'Chinese (Simplified, China)',
  'zh-Hant': 'Chinese (Traditional, Taiwan)',
  'zh-HK': 'Chinese (Hong Kong)',
  'zh-TW': 'Chinese (Traditional)',
  'zh-yue': 'Cantonese',
  'zu': 'Zulu',
};
